version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    network_mode: nginx-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/letsencrypt
      - ./certs:/etc/letsencrypt

  certbot:
    build: .
    container_name: certbot
    volumes:
      - ./:/letsencrypt
      - ./certs:/etc/letsencrypt
    networks:
      - nginx-network
    depends_on:
      - nginx
    entrypoint: ["certbot", "certonly", "--webroot", "--webroot-path=/letsencrypt"]
    # This service will exit after running once
    # To generate a certificate, run:
    # docker-compose run --rm certbot certonly --webroot --webroot-path=/letsencrypt -d yourdomain.com

networks:
  nginx-network:
    name: nginx-network 